/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_example_derongliu_ffmpeg_decoder_FFmpegDecoder */

#ifndef _Included_com_example_derongliu_ffmpeg_decoder_FFmpegDecoder
#define _Included_com_example_derongliu_ffmpeg_decoder_FFmpegDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_derongliu_ffmpeg_decoder_FFmpegDecoder
 * Method:    playVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_derongliu_ffmpeg_decoder_FFmpegDecoder_playVideo
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
