/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_derongliu_opengltest_ffmpeg_FFmpegUtils */

#ifndef _Included_com_example_derongliu_opengltest_ffmpeg_FFmpegUtils
#define _Included_com_example_derongliu_opengltest_ffmpeg_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_derongliu_opengltest_ffmpeg_FFmpegUtils
 * Method:    playVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_example_derongliu_opengltest_ffmpeg_FFmpegUtils_playVideo
        (JNIEnv *, jclass, jstring);

JNIEXPORT void JNICALL Java_com_example_derongliu_opengltest_ffmpeg_FFmpegUtils_setSurface
        (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
