/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_derongliu_opengltest_ffmpeg_FFmpegUtils */

#ifndef _Included_com_example_derongliu_opengltest_ffmpeg_FFmpegUtils
#define _Included_com_example_derongliu_opengltest_ffmpeg_FFmpegUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_derongliu_opengltest_ffmpeg_FFmpegUtils
 * Method:    getFFmpegInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_derongliu_opengltest_ffmpeg_FFmpegUtils_getFFmpegInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
