/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView */
#include <GLES2/gl2.h>

#ifndef _Included_com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView
#define _Included_com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView
 * Method:    onStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL
Java_com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView_onStart
        (JNIEnv *, jobject);

/*
 * Class:     com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView
 * Method:    onStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView_onStop
        (JNIEnv *, jobject);

/*
 * Class:     com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView
 * Method:    setSurface
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL
Java_com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView_setSurface
        (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
