/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView */

#ifndef _Included_com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView
#define _Included_com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView
 * Method:    onStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView_onStart
  (JNIEnv *, jclass);

/*
 * Class:     com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView
 * Method:    onResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView_onResume
  (JNIEnv *, jclass);

/*
 * Class:     com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView
 * Method:    onPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView_onPause
  (JNIEnv *, jclass);

/*
 * Class:     com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView
 * Method:    onStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView_onStop
  (JNIEnv *, jclass);

/*
 * Class:     com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView
 * Method:    setSurface
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_example_derongliu_opengltest_ndk_bysurfaceview_NdkSurfaceView_setSurface
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
