/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_derongliu_opengltest_ndk_byglsurfaceview_NdkGlHelper */
#include <GLES2/gl2.h>
#include <android/log.h>
#include <GLES2/gl2ext.h>

#ifndef _Included_com_example_derongliu_opengltest_ndk_byglsurfaceview_NdkGlHelper
#define _Included_com_example_derongliu_opengltest_ndk_byglsurfaceview_NdkGlHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_derongliu_opengltest_ndk_byglsurfaceview_NdkGlHelper
 * Method:    onSurfaceCreated
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_derongliu_opengltest_ndk_byglsurfaceview_NdkGlHelper_onSurfaceCreated
  (JNIEnv *, jclass);

/*
 * Class:     com_example_derongliu_opengltest_ndk_byglsurfaceview_NdkGlHelper
 * Method:    onSurfaceChanged
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_example_derongliu_opengltest_ndk_byglsurfaceview_NdkGlHelper_onSurfaceChanged
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_example_derongliu_opengltest_ndk_byglsurfaceview_NdkGlHelper
 * Method:    onDrawFrame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_derongliu_opengltest_ndk_byglsurfaceview_NdkGlHelper_onDrawFrame
  (JNIEnv *, jclass);

GLuint CompileShader(GLenum, const char *);

GLuint CreateProgram(const char *, const char *);


#ifdef __cplusplus
}
#endif
#endif
